"""third Migration

Revision ID: 383461911558
Revises: e4c772c8f7ad
Create Date: 2019-03-06 12:30:02.422509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '383461911558'
down_revision = 'e4c772c8f7ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('contacts', sa.String(length=1000), nullable=True))
    op.add_column('companies', sa.Column('services', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'services')
    op.drop_column('companies', 'contacts')
    # ### end Alembic commands ###
