"""second Migration

Revision ID: e4c772c8f7ad
Revises: 2069198a5125
Create Date: 2019-03-06 10:17:09.655096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4c772c8f7ad'
down_revision = '2069198a5125'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('name', sa.String(), nullable=True))
    op.drop_column('companies', 'company_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('companies', 'name')
    # ### end Alembic commands ###
